# Serverless project to sync static website to S3 bucket
service: ${self:custom.config.service_name}

# Plugins
plugins:
  - serverless-s3bucket-sync

# Custom
custom:
  config: ${file(config/default.json)}
  s3-sync:
    - folder: ${self:custom.config.local_sync_folder}
      bucket: ${self:custom.config.website_bucket_name}

# Provider Settings
provider:
  name: aws
  runtime: nodejs6.10
  region: ${self:custom.config.region}
  stage: ${self:custom.config.environment}

# Resources
# resources:
#   Resources:
#       WebsiteSyncBucket:
#         Type: AWS::S3::Bucket
#         Properties:
#           BucketName: ${self:custom.config.website_bucket_name}
#           AccessControl: Private
#           WebsiteConfiguration:
#             IndexDocument: index.html
#             ErrorDocument: error.html
#       WebsiteSyncBucketPolicy:
#         Type: AWS::S3::BucketPolicy
#         DependsOn: WebsiteSyncBucket
#         Properties:
#           Bucket: 
#             Ref: WebsiteSyncBucket
#           PolicyDocument:
#             Version: '2012-10-17'
#             Statement:
#             - Sid: Allow Public Access to All Objects
#               Effect: Allow
#               Principal: '*'
#               Action:
#                 - s3:GetObject
#               Resource: arn:aws:s3:::${self:custom.config.website_bucket_name}/*


#   # Print out the name of the bucket that is created
#   Outputs:
#     WebsiteSyncBucket:
#       Value:
#         Ref: WebsiteSyncBucket